export { default as Root } from "./Table.svelte"
export { default as Body } from "./TableBody.svelte"
export { default as Caption } from "./TableCaption.svelte"
export { default as Cell } from "./TableCell.svelte"
export { default as Head } from "./TableHead.svelte"
export { default as Header } from "./TableHeader.svelte"
export { default as Row } from "./TableRow.svelte"
